name: Build and deploy
on: [push, workflow_dispatch]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/paradicms/paradicms:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          python -m paradicms_etl.pipelines.costume_core_ontology_airtable_to_paradicms_rdf_pipeline \
            --airtable-access-token ${{ secrets.AIRTABLE_ACCESS_TOKEN }} \
            --cache-dir-path ${{ github.workspace}}/.paradicms/cache \
            --force-extract \
            --paradicms-rdf-file-path ${{ github.workspace}}/.paradicms/data/costume_core_ontology.trig
      - uses: paradicms/directory-etl-action@v1-beta
      - run: find ${{ github.workspace}}/.paradicms
      - uses: paradicms/ssg-action@v1-beta
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
